// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqbmcsqomqcuhopikyxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxYm1jc3FvbXFjdWhvcGlreXhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NzA1MzUsImV4cCI6MjA3MTE0NjUzNX0.UCyIr3kzNHx2Q6Egm9yCAKj1QjW7i7lSGL9bETxBfbw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});